### ISSUE TITLE
Android auto

### ISSUE THREAD

**Issue by phken91** [xeon1989/Proton-X50-APK-Installer-GKUI#25]
is this version still support android auto with using [HeadUnit Reloaded by B3IT](https://www.b3itlabs.com/prod.php?id=1)?

**Comment by xeon1989** [comment]
The app support depending on OS.
I do see positive feedback from user that managed to use HUR.
Are you having any issue?

**Comment by phken91** [comment]
Not really, but i am going to crack my x50 and willing to install the `HeadUnit Reloaded`
so just want to make sure the HeadUnit Reloaded is work before i purchase
