### ISSUE TITLE
GKUI to ATLAS

### ISSUE THREAD

**Issue by brorishi** [xeon1989/Proton-X50-APK-Installer-GKUI#29]
Hi Chris,

i had previously downloaded the ATLAS firmware (pre march 2nd) but didnt install it yet. I was clearing my headunit of the current apps when i stupidly selected restore headunit and the download is now gone. Any methods to solve my issue?

**Comment by xeon1989** [comment]
Hello, sorry for late reply.
I believe now you need to install app with ATLAS script.
