### ISSUE TITLE
After installing ES File, it pop out to the homepage...

### ISSUE THREAD

**Issue by PSGoh1** [xeon1989/Proton-X50-APK-Installer-GKUI#30]

**Comment by xeon1989** [comment]
The Es file explorer you installed is not compatible.
Uninstall and change to another one.

**Comment by PSGoh1** [comment]
Hi Chris,

Thanks for the prompt reply.... I tried both ES both are same...

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by xeon1989** [comment]
@PSGoh1 unfortunately it could be both version are not compatible for your case.
Could you check with other GKUI user the compatible version, or get the file from them?

Unfortunately I do not have GKUI IHU to test for you... 🙁
