### ISSUE TITLE
Can't install with Geely Coolray

### ISSUE THREAD

**Issue by danielalvaradob** [xeon1989/Proton-X50-APK-Installer-GKUI#32]
Hi.
I need to know how to install it to Geely Coolray.
Why are you using this? b832bc61472727635baffcf25dd28e9f239273e2
I know how to program, I need to know how to modify the script so it works with my geely coolray

**Comment by danielalvaradob** [comment]
I'm doing all the steps, but when pluggin in my usb, there are no installation or nothing. My USB is FAT32

**Comment by xeon1989** [comment]
Hi, the way to install app might be different in Geely Coolray.
Geely Coolray IHu running on Android KitKat while X90 IHU running on Lollipop.
