### ISSUE TITLE
Thank you, I found it can be used on the car of the Chinese brand Lynk & Co.

### ISSUE THREAD

**Issue by zxy1994** [xeon1989/Proton-X50-APK-Installer-GKUI#33]
Thank you, I found it can be used on the car of the Chinese brand Lynk & Co.   
My car model is Lynk & Co 06 PHEV, and I successfully installed some apps using this shell script.

**Comment by xeon1989** [comment]
Hello @zxy1994 , thanks for your feedback!
I'm quite surprised that it works in other car than Proton/Geely.
By any chance your Lynk & Co 06 PHEV's head unit running on GKUI19?

**Comment by zxy1994** [comment]
![image](https://user-images.githubusercontent.com/22427420/235036582-3c916425-de16-4074-b4be-b4ae3da6f5a3.png)
As shown in the picture above, I used this shell script and successfully installed some apps.

**Comment by zxy1994** [comment]
![image](https://user-images.githubusercontent.com/22427420/235037022-32121f17-a0bc-400c-a5b3-297ed9d02d19.png)
