### ISSUE TITLE
uninstalling the script

### ISSUE THREAD

**Issue by Dranoel231** [xeon1989/Proton-X50-APK-Installer-GKUI#34]
I have been using this script for sometime and recently the Head Unit became laggy and take time load up every time we start the car. It will show apps optimising.

So we decided to try uninstalling the script. But somehow in your post, the uninstalling link when I clicked on it, it leads me to an editing page which shows the same article you written. Could you please let me know how to uninstall it? 

You may reach me at 0166672238 too. 

Thanks.

**Comment by xeon1989** [comment]
Hi, thanks for reporting the link not working.
it supposed to point to specific section of the guide.

I supposed you installed apps on GKUI?
Simply hold the apps until it jiggle, then tap "delete" icon to uninstall it.
